# Generated by Django 4.0.1 on 2022-01-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemSKU', models.CharField(max_length=200)),
                ('itemName', models.CharField(max_length=200)),
                ('itemAmount', models.IntegerField()),
                ('itemAisle', models.CharField(max_length=201)),
            ],
        ),
    ]
